# Generated by Django 4.2.3 on 2025-09-08 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('country', models.CharField(
                    blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(
                    choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'),
                             ('WAGON', 'Wagon'), ('HATCHBACK', 'Hatchback'),
                             ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible')],
                    max_length=20)),
                ('year', models.IntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(2015),
                        django.core.validators.MaxValueValidator(2023)])),
                ('color', models.CharField(blank=True, max_length=50)),
                ('car_make', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='djangoapp.carmake')),
            ],
        ),
    ]
